plugin-prefix: '&f[WW]&3 '
fake-prefix: '&f[FAKE] '

join/leave-management: true
first-join: true
first-join-message: '&f[+] &f&l<player>&3 joined the server for the first time!'
join-message: '&f[+] &f&l<player>&3 joined the server!'
leave-message: '&f[-] &f&l<player>&3 left the server!'

motd-management: true
motd-message:
  - '+--------------------------------------+'
  - ''
  - 'Change this message in the config.yml'
  - ''
  - '+--------------------------------------+'

title-management: true
main-title: '&3Welcome'
sub-title: '&fTo the best server ever!'

tab-management: true
header-tab: '&3&lWarmWelcome'
footer-tab: '&fWelcome &l<player>'