name: WarmWelcome
version: '${project.version}'
main: me.neliz.warmwelcome.WarmWelcome
api-version: '1.19'
authors: [ Neliz ]
description: A join/leave management plugin
website: https://github.com/N3liz/WarmWelcome
commands:
  ww:
    description: Sends a list of plugin commands
    permission: warmwelcome.main
  warmwelcome:
    description: Sends a list of plugin commands
    permission: warmwelcome.main
  fakefirstjoin:
    description: Sends a fake first join message
    permission: warmwelcome.fake.firstjoin
  fakejoin:
    description: Sends a fake join message
    permission: warmwelcome.fake.join
  fakeleave:
    description: Sends a fake leave message
    permission: warmwelcome.fake.leave
permissions:
  warmwelcome.fake:
    children:
      warmwelcome.fake.firstjoin: true
      warmwelcome.fake.join: true
      warmwelcome.fake.leave: true
      warmwelcome.fake.bypass: true
  warmwelcome.reload:
    description: Allows someone to run the reload command
  warmwelcome.fake.firstjoin:
    description: Allows someone to run the fakefirstjoin command
  warmwelcome.fake.join:
    description: Allows someone to run the fakejoin command
  warmwelcome.fake.leave:
    description: Allows someone to run the fakeleave command
  warmwelcome.fake.bypass:
    description: Allows someone to see when messages are fake